enabled: true
ping_offset: 0

enable_message: "&aSuccessfully enabled KnockbackSync."
disable_message: "&cSuccessfully disabled KnockbackSync."
configure_offset_message: "&aSuccessfully configured the ping offset."