name: Build and Version Update

on:
  push:
    branches:
      - main
      - merge
      - dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '17'  # or your preferred Java version
          distribution: 'adopt'

      - name: Generate build number
        id: buildnumber
        uses: einaregilsson/build-number@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Update version in pom.xml and plugin.yml
        id: update_version
        run: |
          VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
          IFS='.' read -ra VERSION_PARTS <<< "$VERSION"
          PATCH=$((VERSION_PARTS[2] + 1))
          NEW_VERSION="${VERSION_PARTS[0]}.${VERSION_PARTS[1]}.$PATCH-dev-b${{ steps.buildnumber.outputs.build_number }}"
          echo "NEW_VERSION=${NEW_VERSION}" >> $GITHUB_ENV
          mvn versions:set -DnewVersion=$NEW_VERSION
          sed -i "s/^version: .*$/version: $NEW_VERSION/" src/main/resources/plugin.yml

      - name: Build with Maven
        run: mvn clean package

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: KnockbackSync-${{ env.NEW_VERSION }}.jar
          path: target/KnockbackSync-${{ env.NEW_VERSION }}.jar
          retention-days: 90

      - uses: Kir-Antipov/mc-publish@v3.3
        with:
          modrinth-id: wGTbjSTq
          modrinth-featured: true
          modrinth-unfeature-mode: subset
          modrinth-token: ${{ secrets.MODRINTH_TOKEN }}

          files: |
            target/KnockbackSync-${{ env.NEW_VERSION }}.jar

          name: KnockbackSync-${{ env.NEW_VERSION }}
          version: ${{ env.NEW_VERSION }}
          version-type: beta

          loaders: |
            bukkit
            spigot
            paper

          game-versions: |
            >=1.18.2

          retry-attempts: 2
          retry-delay: 10000
          fail-mode: fail